export default {
  About : 'Nothing brings your boat or yacht back to life like new interior or exterior upholstery. We repair and re-upholster both interior & exterior marine upholstery, cushions & furniture. We can custom design and also refurbish marine upholstery to the original manufacturer specs. We pride ourselves in being on time, on budget, while delivering the finished product you expect',
  About1 : 'We specialize in constructing high quality custom upholstered outdoor and indoor furniture and/or re-upholstery of sofas, chairs, chaises, ottomans, headboards, bed frames, etc... We create wall upholstery, upholstered wall panels, custom bedding, custom pillows, custom draperies and other types of custom window shades.',
  About2 : 'Need a custom flybridge enclosure for your boat? You can count on us to design, install or repair your bridge enclosure, complete with Strataglass or Isinglass windows which hold up well and look great for many years. For over 10 years, we\'ve been mastering our craft to bring the discerning boat owner top quality craftsmanship using the marine industries\' tried and true materials.',
  About3 : 'ALPHA MARINE UPHOLSTERY, located in PALM COAST FL, has been catering to boaters, fishermen, and the marine industry for over 10 years. We specialize in all types of marine canvas products, including bimini tops, enclosures, dodgers, boat covers, cushions and upholstery. And we\'re happy to re-stitch and repair your existing boat or yacht canvas & upholstery. We\'re convenient to boaters in the harbors area: Daytona Beach, Ormond Beach, Palm Coast, St. Augustine.',
  Phone : 'Phone: 386-276-0294',
  Phone1: '386-276-0284',
  Address1 : `20 Cottonwood court, `,
  Address2 : 'Palm Coast FL 32137',
  Company : 'Alpha Marine Upholstery',
  Email : 'mailto:taran@alphamarineupholstery.com',
  PhoneNumber: 'tel:386-276-0294',
  Short1: 'Nothing brings your boat or yacht back to life like new interior or exterior upholstery...',
  Short2: 'We specialize in constructing high quality custom upholstered outdoor and indoor furniture...',
  Short3: 'Need a custom flybridge enclosure for your boat? You can count on us to design, install...',
} ;
