export default {
  About : 'Having the right replacement battery will help ensure longer life in your watch. Before installing a new watch battery, we want to make sure everything else on the watch is in working order. Something as simple as the stem being pulled out may be the source of a watch not keeping time. We want to make sure that a new battery will solve the problem.',
  About1 : 'We can repair most of your treasured jewelry right in our store. Big job or small, we\'ve got you covered. Just a few of the things we can do for you.',
  Repairs1: ['Ring resizing - we can usually complete the same day, often within an hour','Replace prongs to secure a diamond or color stone','Watch repair'],
  Battery1: ['Large selection of bataies', 'Battery recycling'],
  Phone : 'Phone: 973-636-0019',
  Phone1: '973-636-0019',
  Address1 : '200 Diamond bridge avenue, ',
  Address2 : 'Hawthorne, NJ 07506',
  Company : 'Hawthorne Jewelry',
  Email : 'mailto:hawthornejewelry200@gmail.com',
  Email2 : 'hawthornejewelry200@gmail.com',
  PhoneNumber: 'tel:973-636-0019',
  Short1: 'Hawthorne Jewelry is your source for a huge selection of watch batteries...',
  Short2: 'We can repair most of your treasured jewelry right in our store...',
  Sell1: 'When you sell your gold for 300$ and up you will get one free repair or watch battery replacement',
  Buy1: 'We buy: old, new broke, odd pieces, coins, watches. Just bring it to us and we will give you the best price.',
  Buy2: ['10K - 14K - 18K - 22K', 'diamonds', 'jewelry', 'platinum', 'silver', 'any kind gold and silver coins'],
  Buy1short: 'We buy all gold piceces, silverware, silver, coins and dimonds...',
  Hours: 'Tuesday - Saturday: 10AM to 5PM',
  Work1: 'We buy gold',
  Work2: 'We Repair ALL GOLD & SILVER',
  Work3: 'Watch repair',
  Callus1: 'Call us today if you are looking for something specific. Or stop in to see us. You willll love our dedication to outstanding customer service.'
} ;
